### ISSUE TITLE
c# ButtplugClient events not firing.

### ISSUE THREAD

**Issue by kyrahabattoir** [buttplugio/buttplug-rs-ffi#35]
ButtplugClient:ScanningFinished -> Does not appear to fire when a scan is stopped/finished.
ButtplugClient:ServerDisconnect -> Does not appear to fire when the intiface websocket server is shut down.

It could be my code, but I don't think I've done anything unorthodox.
https://github.com/kyrahabattoir/ToyWebBridge/blob/master/Services/WebsocketService.cs#L112

**Comment by qdot** [comment]
These got wired up in C#, but not in the Rust FFI layer. I'll make new releases of both packages, will clear this bug when those are up on nuget.

**Comment by qdot** [comment]
Wow. Ok, no, it wasn't hooked up in buttplug-rs. This will require a full update from the ground up. Glad someone is testing this stuff 'cause I'm sure not, apparently.

**Comment by qdot** [comment]
Annnnnnd same with ScanningFinished. Only thing that ever registered finishing scans was the Lovense Dongle. Oops.
