### ISSUE TITLE
WebBluetooth: client.AllowedMessages has the wrong datatype

### ISSUE THREAD

**Issue by ftreesmilo** [buttplugio/buttplug-rs-ffi#52]
**Describe the bug**
A clear and concise description of what the bug is. Remember, this should only pertain to bugs at the protocol or general architecture level. Library or application specific bugs should be files in their respective repos.

**Expected behavior**
https://buttplug-js.docs.buttplug.io/classes/buttplugclientdevice.html#allowedmessages

**Actual behavior**
console.dir(device.AllowedMessages)
![image](https://user-images.githubusercontent.com/58193105/105938884-19a1f400-6026-11eb-86d6-7b452bdf8a50.png)

**Comment by qdot** [comment]
Those are the docs for the v0.x series. Removing them now.
