### ISSUE TITLE
js: ButtplugClientDevice.vibrate does not take an array of numbers

### ISSUE THREAD

**Issue by WesleyAC** [buttplugio/buttplug-rs-ffi#59]
Calling `device.vibrate([1.0, 1.0])` results in the error:

```
vibrate can only take numbers or arrays of numbers.
```

The actual behaviour is that `vibrate` can take a number or an array of `VibrationCmd`s. So as not to make breaking changes, it's probably best to change `vibrate` to take either a number, array of numbers, or array of `VibrationCmd`s. Alternatively, the error could be changed to be accurate to the behavior, but taking an array of numbers seems convenient enough to include, and is the documented behaviour elsewhere.

[relevant code](https://github.com/buttplugio/buttplug-rs-ffi/blob/ee9ce0df8652223c90f5615b007eb23b849d60aa/js/src/device.ts#L142-L161)

**Comment by qdot** [comment]
Annnnnnnnd this is why I need to finish implementing test devices for the FFI so we can start getting unit tests in. :|

Thanks for the report! I'll see about getting this fixed up, just need to add an extra check.

**Comment by qdot** [comment]
Fixed and tested in 1.0.13
