### ISSUE TITLE
Buttplug.Endpoint not exported to JS?

### ISSUE THREAD

**Issue by WesleyAC** [buttplugio/buttplug-rs-ffi#60]
**Describe the bug**
When I include Buttplug via `<script lang="javascript" src="https://cdn.jsdelivr.net/npm/buttplug@1.0.12/dist/web/buttplug.min.js"></script>` (or similar), `Buttplug.Endpoint` is `undefined`.

**Expected behavior**
`Buttplug.Endpoint` exists and is usable.

**Actual behavior**
`Buttplug.Endpoing` is `undefined`.

**Comment by qdot** [comment]
Well I *thought* I fixed this in 1.0.13 but I guess not. Reopening.

**Comment by qdot** [comment]
Ok, this is now ACTUALLY fixed in 1.0.14. Buttplug.Endpoint hands back the enum as expected. Thanks for reporting, just let me know if you have any other issues.
