### ISSUE TITLE
Convert public fields to public properties in C# classes

### ISSUE THREAD

**Issue by Yoooi0** [buttplugio/buttplug-rs-ffi#75]
**Feature Description**

Any public facing fields should ideally be converted to a public property. Properties are used in some places but not everywhere, example: 
https://github.com/buttplugio/buttplug-rs-ffi/blob/bf4463a68ba67d89113c2995a1eab2eab006b2c9/csharp/ButtplugCSharpFFI/ButtplugClientDevice.cs#L22-L27

Having `Name` as a field prevents WPF bindings.

**Comment by qdot** [comment]
Landed in C# v2.0.2
