### ISSUE TITLE
Add buttplug_rs_ffi.dll.lib file to windows releases

### ISSUE THREAD

**Issue by sa-wilson** [buttplugio/buttplug-rs-ffi#84]
The MSVC linker requires an import .lib file (just a list of exported symbols) in order to link against a DLL at compile/link time instead of using `LoadLibrary` and `GetProcAddress`, this is already generated by rustc as `buttplug_rs_ffi.dll.lib` - it just needs including in the release archive for windows.

**Comment by qdot** [comment]
Done, v2.0.4 is now in releases, contains the lib file. Lemme know if I need to add anything else.
