### ISSUE TITLE
Buttplug incorrectly states Chrome for Andoird doesn't support the WebBluetooth API

### ISSUE THREAD

**Issue by DXsmiley** [buttplugio/buttplug-rs-ffi#85]
**Describe the bug**
Attempting to start scanning on Chrome for Android produces a console log line stating that the WebBluetooth API isn't supported by the browser. You'll need to setup [remote debugging](https://developer.chrome.com/docs/devtools/remote-debugging/) in order to see it.

**Expected behavior**
Buttplug should start scanning for devices, since [Chrome 91 for Android supports the API](https://caniuse.com/web-bluetooth).

**Additional context**
Tested on Chrome 91 on a Nokia 5.4 on Android 10.
Tested using the version of buttplug hosted at `https://cdn.jsdelivr.net/npm/buttplug@1.0.14/dist/web/buttplug.min.js`

**Minimal example**
```js
// Setup
let connector = new Buttplug.ButtplugEmbeddedConnectorOptions();
let client = new Buttplug.ButtplugClient("Example");
await client.connect(connector);

// Needs to be called in the handler of a user interaction (a button press or something)
// due to browser-enforced security reasons
client.startScanning();
```

**Comment by dumdum7** [comment]
Use HTTPS, it works. Tested on Chrome 97. 
https://developer.mozilla.org/en-US/docs/Web/API/Bluetooth/requestDevice

**Comment by qdot** [comment]
This was actually an issue in chrome that has since been fixed.
